version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: wildfire_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${CLIENT_SECRET}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: wildfire_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/code/app

  frontend:
    build:
      context: ./client/wildfire-ui
      dockerfile: Dockerfile
    container_name: wildfire_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./client/wildfire-ui:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}

volumes: 
  postgres_data: